language: node_js
node_js:
- '4.1'
- '4.0'
deploy:
  provider: npm
  email: philippevoinov@gmail.com
  api_key:
    secure: mkOe7qUngdwT0CXY/scMkAnMLC1drYASERVEvgPK3ijlvQWyRH7CjR7IYBg0Z79uDBnSG9ldTj2b5tsyNWo0e4Sr9IXNMjIZQOli29evAnPl/QpUZgwMYYaAToQg9y+JbMiU0d5W5axYMBN0ffZFP+njVVZPWNO3T7Td94X9hGvT2PU81ziAKls2tXr0GO0zTLZcGkHfKbTyCtmRlYUNV6dBef4gWKT6B4hCgnEq0ZHWyclXC+tWdHShoEhAzPJxJYJVQpdzCw96pi+IOuxleZBWH8t3UI69vUijgDtqhQ+SP2BpgyW3qJppakXGMPcxZemwlxFMrGnSVsm/5OR4xraJH/0lAMQBCrX1m7JhVcwSdkxnrVtAd383S7/CGajc0vMcoiHYiP6Rag0vHiXOcW74Ab5mwte4etGm7CUxGXFfYT43G7niw1EK60+MlDZEjIFhKXez48O5/7XcuRuHs4K3wfWcJXKqzyKkVIAAfhV3kFBGZETY7w0T7cF+rtxkkkFH/+asbApu2aREz5ofnr57sWAlGqjxHCNC3RsM1+gCeNfN3sLJkO7q4gAx1fHfYb/E/Kc+HjoX1F/fOE5ReAm30IIdfMpFWz9MvK4jUjO3LrkocbH3qdc5AJJ/3TbS5HwAFTRHUQav03KgwCXhV2e2Ue8p34DdvpQQdO3WL1E=
  on:
    tags: true
    repo: tehwalris/walris-central
